"use client";
import Link from "next/link";import {useEffect,useMemo,useState} from "react";import {supabase} from "@/lib/supabase";
export default function AdminCampaigns(){const [cs,setCs]=useState<any[]>([]),[filter,setFilter]=useState("all"),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[selected,setSelected]=useState<any|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
async function load(){if(!supabase){setLoading(false);return}setLoading(true);setError("");const {data,error:e}=await supabase.from("campaigns").select("id,advertiser_id,name,goal,instructions,platform,payment_method,payment_rate,max_budget,desired_results,status,funded_amount,created_at,updated_at").order("created_at",{ascending:false});if(e)setError("Could not load campaigns.");setCs(data||[]);setLoading(false)}
useEffect(()=>{load()},[]);
const filtered=useMemo(()=>cs.filter(c=>(filter==="all"||c.status===filter)&&((c.name||"").toLowerCase().includes(query.toLowerCase())||(c.goal||"").toLowerCase().includes(query.toLowerCase())||(c.platform||"").toLowerCase().includes(query.toLowerCase())||(c.payment_method||"").toLowerCase().includes(query.toLowerCase())||c.id.includes(query))),[cs,filter,query]);
async function setStatus(status:string){if(!supabase||!selected)return;setBusy(true);setError("");setMessage("");const {error:e}=await supabase.from("campaigns").update({status,updated_at:new Date().toISOString()}).eq("id",selected.id);if(e)setError("Could not update this campaign.");else{setMessage("Campaign status updated.");setSelected({...selected,status});setCs(prev=>prev.map(c=>c.id===selected.id?{...c,status}:c))}setBusy(false)}
const totalBudget=cs.reduce((a,c)=>a+Number(c.max_budget||0),0),funded=cs.reduce((a,c)=>a+Number(c.funded_amount||0),0),active=cs.filter(c=>c.status==="active").length,paused=cs.filter(c=>c.status==="paused").length;
return <main className="formPage"><Link href="/admin" className="back">← Admin</Link><div className="formCard wide"><span className="eyebrow">ADMIN · CAMPAIGNS</span><h1>Campaign <em>control.</em></h1><p>Monitor every campaign, funding state, progress and marketplace activity.</p>
<div className="statsGrid"><div><b>Active</b><strong>{active}</strong></div><div><b>Paused</b><strong>{paused}</strong></div><div><b>Total</b><strong>{cs.length}</strong></div><div><b>Funded</b><strong>₦{funded.toLocaleString()}</strong></div></div>
<input className="textInput" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search campaign, goal, platform or ID"/>
<div className="choices compact">{["all","active","paused","closed"].map(x=><button key={x} className={filter===x?"selected":""} onClick={()=>setFilter(x)}>{x}</button>)}</div>
{message&&<div className="successBox">✓ {message}</div>}{error&&<div className="successBox">{error}</div>}
{loading?<div className="successBox">Loading campaigns…</div>:<div className="opps">{filtered.map(c=>{const pct=c.max_budget?Math.min(100,Number(c.funded_amount||0)/Number(c.max_budget)*100):0;return <article key={c.id}><b>{String(c.status||"").toUpperCase()}</b><h3>{c.name||"Unnamed campaign"}</h3><p>{c.goal||"No goal"} · {c.platform||"Any platform"} · {c.payment_method||"Payment not set"}</p><strong>₦{Number(c.max_budget||0).toLocaleString()}</strong><p>Funded: ₦{Number(c.funded_amount||0).toLocaleString()} · Rate: ₦{Number(c.payment_rate||0).toLocaleString()} · Target: {c.desired_results||0}</p><div className="successBox">Funding: {pct.toFixed(0)}%</div><button className="secondary" onClick={()=>setSelected(c)}>Manage campaign</button></article>})}{!filtered.length&&<div className="successBox">No campaigns match your search.</div>}</div>}
{selected&&<div className="infoBox"><h2>{selected.name||"Campaign"}</h2><p>{selected.goal||"No goal"} · {selected.platform||"Any platform"}</p><p>Budget: ₦{Number(selected.max_budget||0).toLocaleString()} · Funded: ₦{Number(selected.funded_amount||0).toLocaleString()}</p><p>Payment: {selected.payment_method||"Not set"} at ₦{Number(selected.payment_rate||0).toLocaleString()} · Target: {selected.desired_results||0}</p><p>{selected.instructions||"No creator instructions."}</p><div className="choices compact">{selected.status!=="active"&&<button disabled={busy} onClick={()=>setStatus("active")}>Reopen</button>}{selected.status==="active"&&<button disabled={busy} onClick={()=>setStatus("paused")}>Pause</button>}{selected.status!=="closed"&&<button disabled={busy} onClick={()=>setStatus("closed")}>Close</button>}</div><div className="choices compact"><Link className="secondary" href={"/advertiser/campaigns/"+selected.id+"/edit"}>Edit campaign</Link><Link className="secondary" href={"/advertiser/results?campaign="+selected.id}>View results</Link><Link className="secondary" href={"/advertiser/review?campaign="+selected.id}>Review submissions</Link></div><button className="secondary" onClick={()=>setSelected(null)}>Close panel</button></div>}</div></main>}