"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
type Stats={users:number;creators:number;advertisers:number;campaigns:number;active:number;paused:number;closed:number;submissions:number;pendingReviews:number;payments:number;funded:number;released:number;withdrawals:number;pendingWithdrawals:number};
type Activity={label:string;detail:string;time:string};
export default function Admin(){
 const [stats,setStats]=useState<Stats>({users:0,creators:0,advertisers:0,campaigns:0,active:0,paused:0,closed:0,submissions:0,pendingReviews:0,payments:0,funded:0,released:0,withdrawals:0,pendingWithdrawals:0}),[activity,setActivity]=useState<Activity[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[allow,setAllow]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){if(!supabase){setError("Database connection is not ready.");setLoading(false);return}const [users,campaigns,subs,payments,withdrawals,settings]=await Promise.all([supabase.from("profiles").select("id,role,created_at,display_name").order("created_at",{ascending:false}),supabase.from("campaigns").select("id,name,status,max_budget,funded_amount,created_at").order("created_at",{ascending:false}),supabase.from("submissions").select("id,status,created_at").order("created_at",{ascending:false}),supabase.from("campaign_payments").select("id,amount,status,type,created_at,campaigns(name)").order("created_at",{ascending:false}),supabase.from("creator_withdrawals").select("id,amount,status,created_at").order("created_at",{ascending:false}),supabase.from("platform_settings").select("allow_new_campaigns").eq("id",1).maybeSingle()]);if(users.error||campaigns.error||subs.error||payments.error)setError("Some dashboard data could not be loaded.");const us=users.data||[],cs=campaigns.data||[],ss=subs.data||[],ps=payments.data||[],ws=withdrawals.data||[];setAllow(settings.data?.allow_new_campaigns??true);setStats({users:us.length,creators:us.filter((x:any)=>x.role==="creator").length,advertisers:us.filter((x:any)=>x.role==="advertiser").length,campaigns:cs.length,active:cs.filter((x:any)=>x.status==="active").length,paused:cs.filter((x:any)=>x.status==="paused").length,closed:cs.filter((x:any)=>x.status==="closed").length,submissions:ss.length,pendingReviews:ss.filter((x:any)=>x.status==="submitted").length,payments:ps.length,funded:ps.filter((x:any)=>x.type==="funding").reduce((a:any,x:any)=>a+Number(x.amount||0),0),released:ps.filter((x:any)=>x.status==="released").reduce((a:any,x:any)=>a+Number(x.amount||0),0),withdrawals:ws.length,pendingWithdrawals:ws.filter((x:any)=>x.status==="pending").length});const a:Activity[]=[];cs.slice(0,4).forEach((x:any)=>a.push({label:"Campaign",detail:x.name,time:x.created_at}));ss.slice(0,3).forEach((x:any)=>a.push({label:"Submission",detail:"Creator work submitted",time:x.created_at}));ps.slice(0,3).forEach((x:any)=>a.push({label:"Payment",detail:"₦"+Number(x.amount||0).toLocaleString()+" · "+(x.campaigns?.name||"Campaign"),time:x.created_at}));setActivity(a.sort((x,y)=>new Date(y.time).getTime()-new Date(x.time).getTime()).slice(0,8));setLoading(false)}
 useEffect(()=>{load()},[]);
 async function toggleCampaigns(){if(!supabase)return;setBusy(true);setMessage("");const next=!allow;const {error:e}=await supabase.from("platform_settings").upsert({id:1,allow_new_campaigns:next,updated_at:new Date().toISOString()},{onConflict:"id"});if(e)setError("Couldn't change campaign availability.");else{setAllow(next);setMessage(next?"New campaigns are allowed.":"New campaigns are paused.")}setBusy(false)}
 return <main className="dashboard"><div className="dashTop"><Link href="/" className="back">← AdBridge</Link><span className="testBadge">ADMIN CONTROL CENTER</span><Link href="/advertiser" className="switch">Advertiser →</Link></div><div className="dashHero"><div><span className="eyebrow">ADMIN DASHBOARD</span><h1>Control the <em>marketplace.</em></h1><p>Live overview of users, campaigns, submissions, money, ads and platform controls.</p></div></div>{error&&<div className="successBox">{error}</div>}{message&&<div className="successBox">✓ {message}</div>}<div className="statsGrid"><div><b>Total users</b><strong>{loading?"—":stats.users}</strong><small>{stats.creators} creators · {stats.advertisers} advertisers</small></div><div><b>Campaigns</b><strong>{loading?"—":stats.campaigns}</strong><small>{stats.active} active · {stats.paused} paused · {stats.closed} closed</small></div><div><b>Submissions</b><strong>{loading?"—":stats.submissions}</strong><small>{stats.pendingReviews} waiting for review</small></div><div><b>Payments</b><strong>{loading?"—":"₦"+stats.funded.toLocaleString()}</strong><small>{stats.payments} records · ₦{stats.released.toLocaleString()} released</small></div></div><div className="quickGrid adminGrid"><Link href="/admin/campaigns"><b>◈</b><span>Campaigns</span><small>Review and monitor campaigns</small></Link><Link href="/admin/users"><b>●</b><span>Users</span><small>Creators and advertisers</small></Link><Link href="/admin/payments"><b>₦</b><span>Payments</span><small>Funding and released money</small></Link><Link href="/admin/ads"><b>✦</b><span>Ads</span><small>Universal ad placements</small></Link><Link href="/admin/settings"><b>⚙</b><span>Settings</span><small>Marketplace-wide controls</small></Link><Link href="/admin/withdrawals"><b>↗</b><span>Withdrawals</span><small>{stats.pendingWithdrawals} pending requests</small></Link></div><div className="formCard wide"><span className="eyebrow">QUICK CONTROL</span><h2>Marketplace availability</h2><p>Stop new campaign creation without taking existing campaigns offline.</p><div className="choiceRow"><button className={allow?"primary":"secondary"} disabled={busy} onClick={toggleCampaigns}>{busy?"Saving…":allow?"New campaigns: ON":"New campaigns: OFF"}</button><Link className="secondary" href="/admin/settings">All settings</Link></div></div><div className="formCard wide"><span className="eyebrow">RECENT ACTIVITY</span><h2>What's happening</h2>{loading?<div className="successBox">Loading activity…</div>:activity.length?<div className="opps">{activity.map((x,i)=><article key={i}><b>{x.label.toUpperCase()}</b><h3>{x.detail}</h3><small>{new Date(x.time).toLocaleString()}</small></article>)}</div>:<div className="successBox">No activity yet.</div>}</div></main>
}