"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase";
type Payment={id:string;amount:number|null;type:string|null;status:string|null;created_at:string;campaigns?:{name:string}[]|null};
type Withdrawal={id:string;amount:number;status:string;created_at:string};
export default function Earnings(){
 const [payments,setPayments]=useState<Payment[]>([]),[withdrawals,setWithdrawals]=useState<Withdrawal[]>([]),[amount,setAmount]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 async function load(){if(!supabase){setLoading(false);return}const creatorId=localStorage.getItem("adbridge-creator-id");if(!creatorId){setLoading(false);return}const [p,w]=await Promise.all([supabase.from("campaign_payments").select("id,amount,type,status,created_at,campaigns(name)").eq("creator_id",creatorId).order("created_at",{ascending:false}),supabase.from("creator_withdrawals").select("id,amount,status,created_at").eq("creator_id",creatorId).order("created_at",{ascending:false})]);if(p.error||w.error)setMessage("We couldn't load your payment history.");setPayments((p.data??[]) as Payment[]);setWithdrawals((w.data??[]) as Withdrawal[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const earned=useMemo(()=>payments.filter(p=>["released","approved"].includes(p.status??"")).reduce((s,p)=>s+Number(p.amount||0),0),[payments]);
 const pending=useMemo(()=>payments.filter(p=>["held","pending"].includes(p.status??"")).reduce((s,p)=>s+Number(p.amount||0),0),[payments]);
 const reserved=useMemo(()=>withdrawals.filter(w=>["pending","approved"].includes(w.status)).reduce((s,w)=>s+Number(w.amount||0),0),[withdrawals]);
 const withdrawable=Math.max(0,earned-reserved);
 async function requestWithdrawal(){const creatorId=localStorage.getItem("adbridge-creator-id"),value=Number(amount);if(!supabase||!creatorId)return setMessage("Create your creator profile before requesting payment.");if(!value||value<=0)return setMessage("Enter a valid withdrawal amount.");if(value>withdrawable)return setMessage("That amount is greater than your withdrawable balance.");setBusy(true);const {error}=await supabase.from("creator_withdrawals").insert({creator_id:creatorId,amount:value,status:"pending"});setBusy(false);if(error)return setMessage("Your withdrawal request could not be submitted.");setAmount("");setMessage("Withdrawal request submitted for review.");load()}
 return <main className="formPage"><Link href="/creator" className="back">← Creator Dashboard</Link><div className="formCard wide"><span className="eyebrow">YOUR EARNINGS</span><h1>Your work. Your <em>money.</em></h1><div className="statsGrid"><div><b>Available</b><strong>₦{withdrawable.toLocaleString()}</strong></div><div><b>Pending earnings</b><strong>₦{pending.toLocaleString()}</strong></div><div><b>Withdrawals</b><strong>{withdrawals.length}</strong></div></div><label>How much do you want to withdraw?</label><input className="textInput" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="₦ 0" inputMode="numeric"/><button className="primary" onClick={requestWithdrawal} disabled={busy}>{busy?"Submitting…":"Request withdrawal →"}</button>{message&&<div className="successBox">{message}</div>}<h2>Payment history</h2>{loading?<div className="successBox">Loading payments…</div>:payments.length?<div className="opps">{payments.map(p=><article key={p.id}><b>{(p.status||"pending").toUpperCase()}</b><h3>{p.campaigns?.[0]?.name||"Creator payment"}</h3><p>{(p.type||"payment").replaceAll("_"," ")} · {new Date(p.created_at).toLocaleDateString()}</p><strong>₦{Number(p.amount||0).toLocaleString()}</strong></article>)}</div>:<div className="successBox">No payments yet.</div>}<h2>Withdrawal history</h2>{withdrawals.length?<div className="opps">{withdrawals.map(w=><article key={w.id}><b>{w.status.toUpperCase()}</b><h3>₦{Number(w.amount).toLocaleString()}</h3><small>{new Date(w.created_at).toLocaleString()}</small></article>)}</div>:<div className="successBox">No withdrawal requests yet.</div>}</div></main>
}