"use client";
import Link from "next/link";
import {useState} from "react";
import {supabase} from "@/lib/supabase";

export default function Signup(){
 const [role,setRole]=useState<"creator"|"advertiser">("creator"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[done,setDone]=useState("");
 async function submit(e:React.FormEvent){e.preventDefault();if(!supabase)return setError("Database connection is not configured.");if(password.length<8)return setError("Use a password with at least 8 characters.");setBusy(true);setError("");const {data,error:e1}=await supabase.auth.signUp({email:email.trim(),password});if(e1||!data.user){setError(e1?.message||"Account creation failed.");setBusy(false);return}if(data.session){const {error:e2}=await supabase.from("profiles").insert({id:data.user.id,role,display_name:name.trim(),email:email.trim(),verified:false});if(e2){setError(e2.message);setBusy(false);return}localStorage.setItem("adbridge-user-id",data.user.id);if(role==="creator")localStorage.setItem("adbridge-creator-id",data.user.id);window.location.href=role==="advertiser"?"/advertiser":"/creator";return}setDone("Account created. Check your email to confirm it, then sign in.");setBusy(false)}
 return <main className="formPage"><div className="formCard"><span className="eyebrow">JOIN ADBRIDGE</span><h1>Create your <em>account.</em></h1><p>Choose whether you are hiring creators or creating for brands.</p><div className="choices"><button type="button" className={role==="creator"?"selected":""} onClick={()=>setRole("creator")}>Creator</button><button type="button" className={role==="advertiser"?"selected":""} onClick={()=>setRole("advertiser")}>Advertiser</button></div><form onSubmit={submit}><label>Name / brand name</label><input className="textInput" required value={name} onChange={e=>setName(e.target.value)} /><label>Email</label><input className="textInput" type="email" required value={email} onChange={e=>setEmail(e.target.value)} /><label>Password</label><input className="textInput" type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} />{error&&<div className="successBox">{error}</div>}{done&&<div className="successBox">{done}</div>}<button className="primary fullButton" disabled={busy}>{busy?"Creating…":"Create account →"}</button></form><p>Already registered? <Link href="/login">Sign in</Link></p><Link className="secondary fullButton" href="/">← Back home</Link></div></main>
}