"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase";
export default function Payments(){
 const [rows,setRows]=useState<any[]>([]),[profiles,setProfiles]=useState<any[]>([]),[filter,setFilter]=useState("all"),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function load(){if(!supabase){setLoading(false);return}const [p,u]=await Promise.all([supabase.from("campaign_payments").select("id,campaign_id,creator_id,submission_id,amount,type,status,created_at,campaigns(name)").order("created_at",{ascending:false}),supabase.from("profiles").select("id,display_name,role")]);if(p.error||u.error)setError("Some payment data could not be loaded.");setRows(p.data||[]);setProfiles(u.data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const name=(id:string)=>profiles.find(x=>x.id===id)?.display_name||id||"Not assigned";
 const filtered=rows.filter(r=>(filter==="all"||r.status===filter)&&((r.campaigns?.name||"").toLowerCase().includes(query.toLowerCase())||name(r.creator_id).toLowerCase().includes(query.toLowerCase())||(r.type||"").toLowerCase().includes(query.toLowerCase())));
 const total=rows.reduce((s,r)=>s+Number(r.amount||0),0),held=rows.filter(r=>r.status==="held").reduce((s,r)=>s+Number(r.amount||0),0),released=rows.filter(r=>r.status==="released").reduce((s,r)=>s+Number(r.amount||0),0),pending=rows.filter(r=>r.status==="pending").reduce((s,r)=>s+Number(r.amount||0),0);
 async function setStatus(id:string,status:string){if(!supabase)return;setBusy(id);setError("");const {error:e}=await supabase.from("campaign_payments").update({status}).eq("id",id);if(e)setError("Could not update payment.");else{setMessage("Payment status updated.");await load()}setBusy("")}
 return <main className="formPage"><Link href="/admin" className="back">← Admin</Link><div className="formCard wide"><span className="eyebrow">ADMIN · PAYMENTS</span><h1>Money <em>control.</em></h1><p>Track campaign funding, creator payments and every payment state from one place.</p>
 <div className="statsGrid"><div><b>Total recorded</b><strong>₦{total.toLocaleString()}</strong><small>{rows.length} transactions</small></div><div><b>Held</b><strong>₦{held.toLocaleString()}</strong><small>Campaign funds reserved</small></div><div><b>Released</b><strong>₦{released.toLocaleString()}</strong><small>Creator payments released</small></div><div><b>Pending</b><strong>₦{pending.toLocaleString()}</strong><small>Awaiting processing</small></div></div>
 <input className="textInput" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search campaign, creator or payment type"/>
 <div className="choices compact">{["all","held","pending","released","approved","refunded","cancelled"].map(x=><button key={x} className={filter===x?"selected":""} onClick={()=>setFilter(x)}>{x}</button>)}</div>
 {error&&<div className="successBox">{error}</div>}{message&&<div className="successBox">✓ {message}</div>}
 {loading?<div className="successBox">Loading payments…</div>:<div className="opps">{filtered.map(r=><article key={r.id}><b>{String(r.status||"pending").toUpperCase()}</b><h3>{r.campaigns?.name||"Payment"}</h3><p>{(r.type||"payment").replaceAll("_"," ")} · Creator: {name(r.creator_id)}</p><small>{new Date(r.created_at).toLocaleString()} {r.submission_id?"· linked to submission":""}</small><strong>₦{Number(r.amount||0).toLocaleString()}</strong>{["held","pending"].includes(r.status)&&<div className="choiceRow"><button className="primary" disabled={busy===r.id} onClick={()=>setStatus(r.id,"released")}>{busy===r.id?"Saving…":"Release payment"}</button><button className="secondary" disabled={busy===r.id} onClick={()=>setStatus(r.id,"cancelled")}>Cancel</button></div>}{r.status==="released"&&<button className="secondary" disabled={busy===r.id} onClick={()=>setStatus(r.id,"refunded")}>Mark refunded</button>}</article>)}{!filtered.length&&<div className="successBox">No payments match this filter.</div>}</div>}</div></main>
}