"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { supabase } from "@/lib/supabase";
type Placement={id:string;name:string;placement_key:string;description:string|null;enabled:boolean;format:string;provider:string|null;campaign_id:string|null;icon:string|null;action_url:string|null;frequency_cap:number;target_pages:string[]};
const formats=[["direct_sponsor","Direct sponsor"],["banner","Banner"],["interstitial","Interstitial"],["rewarded","Rewarded"],["playable","Playable"],["offerwall","Offerwall / game"],["link","Link ad"]];
const pages=["Main Feed","Messages","Creator Work","Results","Campaigns","Dashboard"];
export default function Ads(){
 const [rows,setRows]=useState<Placement[]>([]),[selected,setSelected]=useState<Placement|null>(null),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function load(){if(!supabase){setError("Database connection is not ready.");setLoading(false);return}const {data,error:e}=await supabase.from("ad_placements").select("*").order("created_at",{ascending:true});if(e)setError("We couldn't load ad placements.");else setRows(data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function save(){if(!supabase||!selected)return;setSaving(true);setMessage("");const {error:e}=await supabase.from("ad_placements").update({name:selected.name,description:selected.description,enabled:selected.enabled,format:selected.format,provider:selected.provider,icon:selected.icon,action_url:selected.action_url,frequency_cap:Number(selected.frequency_cap)||0,target_pages:selected.target_pages,updated_at:new Date().toISOString()}).eq("id",selected.id);if(e)setError("We couldn't save this placement.");else{setMessage("Placement saved.");await load()}setSaving(false)}
 function togglePage(p:string){if(!selected)return;setSelected({...selected,target_pages:selected.target_pages.includes(p)?selected.target_pages.filter(x=>x!==p):[...selected.target_pages,p]})}
 return <main className="formPage"><Link href="/admin" className="back">← Admin</Link><div className="formCard wide"><span className="eyebrow">ADMIN · ADS</span><h1>Control every <em>ad placement.</em></h1><p>One reusable placement can serve different ad formats. Change the format here without rebuilding the app.</p>{loading&&<div className="successBox">Loading placements…</div>}{error&&<div className="successBox">{error}</div>}{message&&<div className="successBox">✓ {message}</div>}
 {!loading&&<div className="opps">{rows.map(r=><article key={r.id}><b>{r.enabled?"ON":"OFF"}</b><h3>{r.name}</h3><p>{r.description||"Reusable advertising slot"} · <strong>{r.format.replaceAll("_"," ")}</strong></p><small>{r.provider||"No provider"} · Cap: {r.frequency_cap||"No cap"} · {r.target_pages.join(", ")||"No pages"}</small><button className="secondary" onClick={()=>setSelected({...r})}>Manage placement</button></article>)}</div>}
 {selected&&<div className="infoBox"><h2>{selected.name}</h2><label>Placement name</label><input className="textInput" value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})}/><label>Description</label><textarea value={selected.description||""} onChange={e=>setSelected({...selected,description:e.target.value})}/><label>Active</label><div className="choices compact"><button type="button" className={selected.enabled?"selected":""} onClick={()=>setSelected({...selected,enabled:true})}>On</button><button type="button" className={!selected.enabled?"selected":""} onClick={()=>setSelected({...selected,enabled:false})}>Off</button></div><label>Ad format</label><div className="choices compact">{formats.map(([id,title])=><button type="button" key={id} className={selected.format===id?"selected":""} onClick={()=>setSelected({...selected,format:id})}>{title}</button>)}</div><label>Provider</label><input className="textInput" value={selected.provider||""} onChange={e=>setSelected({...selected,provider:e.target.value})} placeholder="Direct Sponsor, Ad provider, etc."/><label>Action link</label><input className="textInput" value={selected.action_url||""} onChange={e=>setSelected({...selected,action_url:e.target.value})} placeholder="Optional destination"/><label>Frequency cap per user</label><input className="textInput" inputMode="numeric" value={selected.frequency_cap} onChange={e=>setSelected({...selected,frequency_cap:Number(e.target.value)||0})}/><label>Show on</label><div className="choices compact">{pages.map(p=><button type="button" key={p} className={selected.target_pages.includes(p)?"selected":""} onClick={()=>togglePage(p)}>{p}</button>)}</div><div className="choiceRow"><button className="primary" disabled={saving} onClick={save}>{saving?"Saving…":"Save placement"}</button><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div></div>}</div></main>}