"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
type Placement={id:string;name:string;placement_key:string;description:string|null;enabled:boolean;format:string;provider:string|null;campaign_id:string|null;icon:string|null;action_url:string|null;frequency_cap:number;target_pages:string[];starts_at:string|null;ends_at:string|null};
const formats=[["direct_sponsor","Direct sponsor"],["banner","Banner"],["interstitial","Interstitial"],["rewarded","Rewarded"],["playable","Playable"],["offerwall","Offerwall / game"],["link","Link ad"]];
const pages=["Main Feed","Messages","Creator Work","Results","Campaigns","Dashboard"];
export default function Ads(){const [rows,setRows]=useState<Placement[]>([]),[campaigns,setCampaigns]=useState<any[]>([]),[selected,setSelected]=useState<Placement|null>(null),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[error,setError]=useState("");
async function load(){if(!supabase){setError("Database connection is not ready.");setLoading(false);return}const [a,c]=await Promise.all([supabase.from("ad_placements").select("*").order("created_at",{ascending:true}),supabase.from("campaigns").select("id,name,status").order("created_at",{ascending:false})]);if(a.error)setError("We couldn't load ad placements.");else setRows(a.data||[]);setCampaigns(c.data||[]);setLoading(false)}
useEffect(()=>{load()},[]);
async function save(){if(!supabase||!selected)return;setSaving(true);setMessage("");setError("");const payload={name:selected.name,description:selected.description,enabled:selected.enabled,format:selected.format,provider:selected.provider,campaign_id:selected.campaign_id||null,icon:selected.icon,action_url:selected.action_url,frequency_cap:Number(selected.frequency_cap)||0,target_pages:selected.target_pages,starts_at:selected.starts_at||null,ends_at:selected.ends_at||null,updated_at:new Date().toISOString()};const {error:e}=await supabase.from("ad_placements").update(payload).eq("id",selected.id);if(e)setError("We couldn't save this placement.");else{setMessage("Placement saved.");await load();setSelected(null)}setSaving(false)}
function togglePage(p:string){if(!selected)return;setSelected({...selected,target_pages:selected.target_pages.includes(p)?selected.target_pages.filter(x=>x!==p):[...selected.target_pages,p]})}
return <main className="formPage"><Link href="/admin" className="back">← Admin</Link><div className="formCard wide"><span className="eyebrow">ADMIN · ADS</span><h1>Control every <em>ad placement.</em></h1><p>One reusable placement can serve different ad formats, providers, campaigns and schedules.</p>
<div className="statsGrid"><div><b>Total</b><strong>{rows.length}</strong></div><div><b>Active</b><strong>{rows.filter(r=>r.enabled).length}</strong></div><div><b>Scheduled</b><strong>{rows.filter(r=>r.starts_at||r.ends_at).length}</strong></div></div>
{loading&&<div className="successBox">Loading placements…</div>}{error&&<div className="successBox">{error}</div>}{message&&<div className="successBox">✓ {message}</div>}
{!loading&&<div className="opps">{rows.map(r=><article key={r.id}><b>{r.enabled?"ON":"OFF"}</b><h3>{r.name}</h3><p>{r.description||"Reusable advertising slot"} · <strong>{r.format.replaceAll("_"," ")}</strong></p><small>{r.provider||"No provider"} · Cap: {r.frequency_cap||"No cap"} · {r.target_pages.join(", ")||"No pages"}</small>{(r.starts_at||r.ends_at)&&<small>Schedule: {r.starts_at?new Date(r.starts_at).toLocaleString():"Any time"} → {r.ends_at?new Date(r.ends_at).toLocaleString():"No end"}</small>}<button className="secondary" onClick={()=>setSelected({...r})}>Manage placement</button></article>)}</div>}
{selected&&<div className="infoBox"><h2>{selected.name}</h2><label>Placement name</label><input className="textInput" value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})}/><label>Description</label><textarea value={selected.description||""} onChange={e=>setSelected({...selected,description:e.target.value})}/><label>Active</label><div className="choices compact"><button type="button" className={selected.enabled?"selected":""} onClick={()=>setSelected({...selected,enabled:true})}>On</button><button type="button" className={!selected.enabled?"selected":""} onClick={()=>setSelected({...selected,enabled:false})}>Off</button></div><label>Ad format</label><div className="choices compact">{formats.map(([id,title])=><button type="button" key={id} className={selected.format===id?"selected":""} onClick={()=>setSelected({...selected,format:id})}>{title}</button>)}</div><label>Provider</label><input className="textInput" value={selected.provider||""} onChange={e=>setSelected({...selected,provider:e.target.value})} placeholder="Direct Sponsor, provider name, etc."/><label>Linked campaign</label><select className="textInput" value={selected.campaign_id||""} onChange={e=>setSelected({...selected,campaign_id:e.target.value||null})}><option value="">No campaign</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name} · {c.status}</option>)}</select><label>Icon / label</label><input className="textInput" value={selected.icon||""} onChange={e=>setSelected({...selected,icon:e.target.value})} placeholder="Optional icon or short label"/><label>Action link</label><input className="textInput" value={selected.action_url||""} onChange={e=>setSelected({...selected,action_url:e.target.value})} placeholder="Optional destination"/><label>Frequency cap per user (0 = unlimited)</label><input className="textInput" inputMode="numeric" value={selected.frequency_cap} onChange={e=>setSelected({...selected,frequency_cap:Number(e.target.value)||0})}/><label>Start time</label><input className="textInput" type="datetime-local" value={selected.starts_at?new Date(selected.starts_at).toISOString().slice(0,16):""} onChange={e=>setSelected({...selected,starts_at:e.target.value?new Date(e.target.value).toISOString():null})}/><label>End time</label><input className="textInput" type="datetime-local" value={selected.ends_at?new Date(selected.ends_at).toISOString().slice(0,16):""} onChange={e=>setSelected({...selected,ends_at:e.target.value?new Date(e.target.value).toISOString():null})}/><label>Show on</label><div className="choices compact">{pages.map(p=><button type="button" key={p} className={selected.target_pages.includes(p)?"selected":""} onClick={()=>togglePage(p)}>{p}</button>)}</div><div className="choiceRow"><button className="primary" disabled={saving} onClick={save}>{saving?"Saving…":"Save placement"}</button><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div></div>}</div></main>}