"use client";
import Link from "next/link";import{useSearchParams}from"next/navigation";import{useState}from"react";

const goals=[["video","Make and post a video","Creators make content about my product and post it."],["traffic","Bring people to my website","Creators send real people to my website."],["installs","Get app installs","Creators help people discover and install my app."],["product","Show my product in videos","My product appears naturally inside creator content."],["sales","Get sign-ups or purchases","Creators help me get a specific action."],["views","Get my ad seen","I want people to see my campaign."],["other","Something else","I have a different campaign idea."]];
const formats=[["web","Web","Website / browser"],["web_app","Web App","Web application"],["android_app","Android App","Android application"],["ios_app","iOS App","iPhone / iPad application"]];

export default function Details(){const p=useSearchParams();const goal=p.get("goal")||"video";const[name,setName]=useState(""),[instructions,setInstructions]=useState(""),[platform,setPlatform]=useState("TikTok"),[assets,setAssets]=useState<string[]>([]),[destination,setDestination]=useState(""),[selectedFormats,setSelectedFormats]=useState<string[]>(["web"]);
const toggle=(x:string)=>setAssets(a=>a.includes(x)?a.filter(v=>v!==x):[...a,x]);
const toggleFormat=(x:string)=>setSelectedFormats(a=>a.includes(x)?a.filter(v=>v!==x):[...a,x]);
const allSelected=selectedFormats.length===formats.length;
const toggleAll=()=>setSelectedFormats(allSelected?[]:formats.map(f=>f[0]));
const next="/advertiser/new/payment?goal="+encodeURIComponent(goal)+"&platform="+encodeURIComponent(platform)+"&name="+encodeURIComponent(name)+"&instructions="+encodeURIComponent(instructions)+"&assets="+encodeURIComponent(assets.join(","))+"&destination="+encodeURIComponent(destination)+"&formats="+encodeURIComponent(selectedFormats.join(","));
const platforms=["TikTok","Instagram Reels","YouTube","YouTube Shorts","Facebook","Facebook Reels","X","Snapchat"];
return <main className="formPage"><Link href={"/advertiser/new?goal="+encodeURIComponent(goal)} className="back">← Back</Link><div className="formCard wide"><span className="eyebrow">STEP 2 OF 5</span><h1>Tell creators exactly <em>what to do.</em></h1><p>Creators see these instructions before accepting your campaign.</p><label>Campaign name</label><input className="textInput" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Summer product launch"/><label>What should the creator do?</label><textarea value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Example: Make a 30–60 second video showing the product and follow the campaign brief."/><label>What can you provide?</label><div className="choices compact">{["Product photos/video","Product or sample","Logo + brand assets","Website/app link"].map(x=><button type="button" key={x} className={assets.includes(x)?"selected":""} onClick={()=>toggle(x)}>{x}</button>)}</div><label>Where should the creator post?</label><div className="choices compact">{platforms.map(x=><button type="button" key={x} className={platform===x?"selected":""} onClick={()=>setPlatform(x)}>{x}</button>)}</div>
<label>Where would you like this ad to be displayed?</label><p className="fieldHint">Choose one, several, or All formats. AdBridge prepares only the formats you select.</p><div className="formatChoiceGrid"><button type="button" className={"formatChoice all "+(allSelected?"selected":"")} onClick={toggleAll}><strong>All formats</strong><small>Web + Web App + Android App + iOS App</small></button>{formats.map(([id,title,desc])=><button type="button" key={id} className={"formatChoice "+(selectedFormats.includes(id)?"selected":"")} onClick={()=>toggleFormat(id)}><strong>{title}</strong><small>{desc}</small></button>)}</div>
{selectedFormats.length===0&&<div className="successBox">Select at least one delivery format.</div>}
{["traffic","installs","sales"].includes(goal)&&<><label>Website / app destination URL</label><input className="textInput" value={destination} onChange={e=>setDestination(e.target.value)} placeholder="https://example.com"/></>}<Link className={"primary "+(selectedFormats.length===0?"disabledLink":"")} href={selectedFormats.length?next:"#"} onClick={e=>{if(!selectedFormats.length)e.preventDefault()}}>Continue →</Link></div></main>}
