"use client";
import Link from "next/link";import{useSearchParams}from"next/navigation";import{useState}from"react";import{supabase}from"@/lib/supabase";
const assetMap:Record<string,string>={"Product photos/video":"product_media","Product or sample":"sample","Logo + brand assets":"brand_assets","Website/app link":"website_app_link"};
export default function Fund(){const p=useSearchParams();const[campaignId,setCampaignId]=useState(""),[saving,setSaving]=useState(false),[paying,setPaying]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false);
const goal=p.get("goal")||"video",platform=p.get("platform")||"TikTok",method=p.get("method")||"job";const name=p.get("name")||"Untitled campaign",instructions=p.get("instructions")||"",assets=p.get("assets")||"",destination=p.get("destination")||"",rate=p.get("rate")||"0",budget=p.get("budget")||"0",results=p.get("results")||"0";
const label=method==="cpm"?"CPM":method==="cpc"?"CPC":method==="cpi"?"CPI":method==="cpa"?"CPA":method==="link_traffic"?"Link traffic":method==="product_placement"?"Product placement":method==="brand_mention"?"Brand mention":method==="partnership"?"Partnership":"Creator post/job";
async function createCampaign(){if(!supabase){setError("Database connection is not ready.");return}const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login";return}if(!name.trim()||!instructions.trim()){setError("Add a campaign name and clear creator instructions first.");return}if(Number(budget)<=0){setError("Enter a maximum campaign budget greater than zero.");return}if(["cpc","link_traffic","cpi","cpa"].includes(method)&&Number(results)<=0){setError("Enter a target result greater than zero.");return}if(["cpc","link_traffic","cpa","cpi"].includes(method)){try{const u=new URL(destination);if(!["http:","https:"].includes(u.protocol))throw 0}catch{setError("Add a valid website destination URL.");return}}setSaving(true);setError("");
const{data:settings}=await supabase.from("platform_settings").select("allow_new_campaigns").eq("id",1).maybeSingle();if(settings&&!settings.allow_new_campaigns){setError("New campaigns are temporarily disabled by AdBridge.");setSaving(false);return}
const{data,error:e}=await supabase.from("campaigns").insert({name,goal,instructions,platform,payment_method:method,payment_rate:Number(rate)||0,max_budget:Number(budget)||0,desired_results:Number(results.replaceAll(",",""))||0,advertiser_id:user.id,status:"draft",funded_amount:0}).select("id").single();if(e){setError(e.message||"We couldn't create the campaign yet.");setSaving(false);return}setCampaignId(data.id);
if(["cpc","link_traffic"].includes(method)){const{error:de}=await supabase.from("campaign_destination_urls").insert({campaign_id:data.id,target_url:destination.trim()});if(de){setError("Campaign created, but its destination URL could not be saved.");setSaving(false);return}}
const selectedAssets=assets.split(",").map(x=>assetMap[x]).filter(Boolean);if(selectedAssets.length)await supabase.from("campaign_assets").insert(selectedAssets.map(asset_type=>({campaign_id:data.id,asset_type})));
const{error:testError}=await supabase.from("campaign_tests").insert({campaign_id:data.id,test_type:"understanding",title:"Campaign understanding check",instructions:"Read the advertiser instructions carefully. Confirm that you understand what must be shown, said, posted, linked or achieved before accepting the campaign.",action_label:"Complete understanding check",required:true});if(testError){setError("Campaign was created, but its creator test could not be saved.");setSaving(false);return}
await supabase.from("campaign_tracking_rules").upsert({campaign_id:data.id,track_views:method==="cpm",track_clicks:["cpc","link_traffic"].includes(method),track_installs:method==="cpi",track_signups:method==="cpa",track_purchases:method==="cpa",track_leads:method==="cpa",track_traffic:["cpc","link_traffic"].includes(method),fraud_detection:true},{onConflict:"campaign_id"});setSaved(true);setSaving(false)}
async function pay(){if(!supabase||!campaignId)return;setPaying(true);setError("");const{data,error}=await supabase.functions.invoke("start-campaign-payment",{body:{campaign_id:campaignId}});if(error||data?.error){setError(data?.error||error?.message||"Payment could not be started.");setPaying(false);return}if(data?.authorization_url)location.href=data.authorization_url;else setError("Payment provider did not return a checkout URL.");setPaying(false)}
return <main className="formPage"><Link href={"/advertiser/new/payment?goal="+encodeURIComponent(goal)+"&platform="+encodeURIComponent(platform)} className="back">← Payment</Link><div className="formCard wide"><span className="eyebrow">STEP 4 OF 5</span><h1>Review and <em>fund your campaign.</em></h1><p>Review the campaign before saving it. Payment is handled by a configured provider.</p><div className="summary"><b>{name}</b><span>Platform: {platform}</span><span>Payment model: {label}</span><span>Rate / fee: ₦{Number(rate||0).toLocaleString()}</span><span>Maximum budget: ₦{Number(budget||0).toLocaleString()}</span></div><div className="infoBox"><b>Real payment only</b><p>AdBridge will never mark a campaign funded because a budget was entered. A campaign becomes funded only after the payment provider confirms the payment.</p></div>{error&&<div className="successBox">{error}</div>}{!saved?<button className="primary fullButton" disabled={saving} onClick={createCampaign}>{saving?"Saving campaign…":"Save campaign draft →"}</button>:<><div className="successBox"><b>Draft saved.</b><br/>Your campaign is not live yet. Complete payment to fund it.</div><button className="primary fullButton" disabled={paying} onClick={pay}>{paying?"Opening secure checkout…":"Pay securely with Paystack →"}</button><Link className="secondary fullButton" href="/advertiser">Keep as draft</Link></>}</div></main>}