"use client";
import Link from "next/link";import{useSearchParams}from"next/navigation";import{useState}from"react";import{supabase}from"@/lib/supabase";
const assetMap:Record<string,string>={"Product photos/video":"product_media","Product or sample":"sample","Logo + brand assets":"brand_assets","Website/app link":"website_app_link"};
export default function Fund(){const p=useSearchParams();const[campaignId,setCampaignId]=useState(""),[saving,setSaving]=useState(false),[paying,setPaying]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false);
const goal=p.get("goal")||"video",platforms=p.get("platforms")||"tiktok",method=p.get("method")||"job",formats=p.get("formats")||"web";const name=p.get("name")||"Untitled campaign",instructions=p.get("instructions")||"",assets=p.get("assets")||"",destination=p.get("destination")||"",rate=p.get("rate")||"0",budget=p.get("budget")||"0",results=p.get("results")||"0";
const platformMeta:Record<string,{label:string}>={instagram:{label:"Instagram"},tiktok:{label:"TikTok"},youtube:{label:"YouTube"},facebook:{label:"Facebook"},x:{label:"X"},snapchat:{label:"Snapchat"},linkedin:{label:"LinkedIn"},website:{label:"Website"},web_app:{label:"Web App"},android_app:{label:"Android App"},ios_app:{label:"iOS App"},mobile_app:{label:"Mobile App"}};
const selectedPlatforms=platforms.split(",").map(x=>x.trim()).filter(x=>platformMeta[x]);
const label=method==="cpm"?"CPM":method==="cpc"?"CPC":method==="cpi"?"CPI":method==="cpa"?"CPA":method==="link_traffic"?"Link traffic":method==="product_placement"?"Product placement":method==="brand_mention"?"Brand mention":method==="partnership"?"Partnership":"Creator post/job";
async function createCampaign(){if(!supabase){setError("Database connection is not ready.");return}const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login";return}if(!name.trim()||!instructions.trim()){setError("Add a campaign name and clear creator instructions first.");return}if(Number(budget)<=0){setError("Enter a maximum campaign budget greater than zero.");return}if(["cpc","link_traffic","cpi","cpa"].includes(method)&&Number(results)<=0){setError("Enter a target result greater than zero.");return}if(["cpc","link_traffic","cpa","cpi"].includes(method)){try{const u=new URL(destination);if(!["http:","https:"].includes(u.protocol))throw 0}catch{setError("Add a valid website destination URL.");return}}setSaving(true);setError("");
const{data:settings}=await supabase.from("platform_settings").select("allow_new_campaigns").eq("id",1).maybeSingle();if(settings&&!settings.allow_new_campaigns){setError("New campaigns are temporarily disabled by AdBridge.");setSaving(false);return}
const legacyPlatform=selectedPlatforms.length===Object.keys(platformMeta).length?"all":selectedPlatforms.length===1?selectedPlatforms[0]:"multiple";
const{data,error:e}=await supabase.from("campaigns").insert({name,goal,instructions,platform:legacyPlatform,payment_method:method,payment_rate:Number(rate)||0,max_budget:Number(budget)||0,desired_results:Number(results.replaceAll(",",""))||0,advertiser_id:user.id,status:"draft",funded_amount:0}).select("id").single();if(e){setError(e.message||"We couldn't create the campaign yet.");setSaving(false);return}setCampaignId(data.id);const platformList=platforms.split(",").map(x=>x.trim()).filter(Boolean);if(!platformList.length){setError("Select at least one target platform.");setSaving(false);return}const{error:platformError}=await supabase.from("campaign_platforms").insert(platformList.map(platform=>({campaign_id:data.id,platform})));if(platformError){setError("Campaign created, but its target platforms could not be saved.");setSaving(false);return}
const{error:platformError}=await supabase.from("campaign_platforms").insert(selectedPlatforms.map(platform=>({campaign_id:data.id,platform,enabled:true})));
if(platformError){setError("Campaign created, but its platform targeting could not be saved.");setSaving(false);return}if(platformError){setError("Campaign created, but its platform targeting could not be saved.");setSaving(false);return}
if(["cpc","link_traffic"].includes(method)){const{error:de}=await supabase.from("campaign_destination_urls").insert({campaign_id:data.id,target_url:destination.trim()});if(de){setError("Campaign created, but its destination URL could not be saved.");setSaving(false);return}}
const formatMeta:Record<string,{integration_type:string;requirements:string}>={
web:{integration_type:"web_embed",requirements:"Requires a website or browser-based placement."},
web_banner:{integration_type:"web_embed",requirements:"Requires a website banner placement."},web_native:{integration_type:"web_native",requirements:"Requires a website native placement."},web_interstitial:{integration_type:"web_interstitial",requirements:"Requires a website full-screen placement."},web_video:{integration_type:"web_video",requirements:"Requires a website video placement."},
web_app:{integration_type:"web_app_package",requirements:"Requires a web app or web application placement."},
app_banner:{integration_type:"app_banner",requirements:"Requires an app banner placement."},app_native:{integration_type:"app_native",requirements:"Requires an app native placement."},app_interstitial:{integration_type:"app_interstitial",requirements:"Requires an app full-screen placement."},app_video:{integration_type:"app_video",requirements:"Requires an in-app video placement."},app_rewarded_video:{integration_type:"app_rewarded_video",requirements:"Requires an in-app rewarded video placement."},
android_app:{integration_type:"android_adapter",requirements:"Requires an Android app placement. AdBridge prepares the Android delivery package; native SDK/provider wiring may be required where applicable."},
ios_app:{integration_type:"ios_adapter",requirements:"Requires an iOS app placement. AdBridge prepares the iOS delivery package; native SDK/provider wiring may be required where applicable."},
social_post:{integration_type:"social_post",requirements:"Requires a supported social publishing destination."},social_story:{integration_type:"social_story",requirements:"Requires a supported social story destination."},social_reel:{integration_type:"social_reel",requirements:"Requires a supported social reel destination."},social_video:{integration_type:"social_video",requirements:"Requires a supported social video destination."}
};
const selectedFormats=formats.split(",").map(x=>x.trim()).filter(x=>formatMeta[x]);
if(!selectedPlatforms.length){setError("Select at least one campaign platform.");setSaving(false);return}
if(!selectedFormats.length){setError("Select at least one AdBridge delivery format.");setSaving(false);return}
const{error:formatError}=await supabase.from("campaign_formats").insert(selectedFormats.map(format=>({campaign_id:data.id,format,status:"ready",integration_type:formatMeta[format].integration_type,requirements:formatMeta[format].requirements})));
if(formatError){setError("Campaign created, but its delivery formats could not be saved.");setSaving(false);return}
const selectedAssets=assets.split(",").map(x=>assetMap[x]).filter(Boolean);if(selectedAssets.length)await supabase.from("campaign_assets").insert(selectedAssets.map(asset_type=>({campaign_id:data.id,asset_type})));
const{error:testError}=await supabase.from("campaign_tests").insert({campaign_id:data.id,test_type:"understanding",title:"Campaign understanding check",instructions:"Read the advertiser instructions carefully. Confirm that you understand what must be shown, said, posted, linked or achieved before accepting the campaign.",action_label:"Complete understanding check",required:true});if(testError){setError("Campaign was created, but its creator test could not be saved.");setSaving(false);return}
await supabase.from("campaign_tracking_rules").upsert({campaign_id:data.id,track_views:method==="cpm",track_clicks:["cpc","link_traffic"].includes(method),track_installs:method==="cpi",track_signups:method==="cpa",track_purchases:method==="cpa",track_leads:method==="cpa",track_traffic:["cpc","link_traffic"].includes(method),fraud_detection:true},{onConflict:"campaign_id"});setSaved(true);setSaving(false)}
async function pay(){if(!supabase||!campaignId)return;setPaying(true);setError("");const{data,error}=await supabase.functions.invoke("start-campaign-payment",{body:{campaign_id:campaignId}});if(error||data?.error){setError(data?.error||error?.message||"Payment could not be started.");setPaying(false);return}if(data?.authorization_url)location.href=data.authorization_url;else setError("Payment provider did not return a checkout URL.");setPaying(false)}
return <main className="formPage"><Link href={"/advertiser/new/payment?goal="+encodeURIComponent(goal)+"&platforms="+encodeURIComponent(platforms)} className="back">← Payment</Link><div className="formCard wide"><span className="eyebrow">STEP 4 OF 5</span><h1>Review and <em>fund your campaign.</em></h1><p>Review the campaign before saving it. Payment is handled by a configured provider.</p><div className="summary"><b>{name}</b><span>Campaign platforms: {selectedPlatforms.map(x=>platformMeta[x]?.label||x).join(" · ")}</span><span>Ad delivery formats: {formats.split(",").filter(Boolean).map(x=>({web_banner:"Web Banner",web_native:"Web Native",web_interstitial:"Web Interstitial",web_video:"Web Video",web:"Web",web_app:"Web App",app_banner:"App Banner",app_native:"App Native",app_interstitial:"App Interstitial",app_video:"App Video",app_rewarded_video:"Rewarded Video",android_app:"Android App",ios_app:"iOS App",social_post:"Social Post",social_story:"Social Story",social_reel:"Social Reel",social_video:"Social Video"} as Record<string,string>)[x]||x).join(" · ")}</span><span>Payment model: {label}</span><span>Rate / fee: ₦{Number(rate||0).toLocaleString()}</span><span>Maximum budget: ₦{Number(budget||0).toLocaleString()}</span></div><div className="infoBox"><b>Real payment only</b><p>AdBridge will never mark a campaign funded because a budget was entered. A campaign becomes funded only after the payment provider confirms the payment.</p></div>{error&&<div className="successBox">{error}</div>}{!saved?<button className="primary fullButton" disabled={saving} onClick={createCampaign}>{saving?"Saving campaign…":"Save campaign draft →"}</button>:<><div className="successBox"><b>Draft saved.</b><br/>Your campaign is not live yet. Complete payment to fund it.</div><button className="primary fullButton" disabled={paying} onClick={pay}>{paying?"Opening secure checkout…":"Pay securely with Paystack →"}</button><Link className="secondary fullButton" href="/advertiser">Keep as draft</Link></>}</div></main>}