"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
export default function AdminReview(){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function load(){if(!supabase)return;const {data,error:e}=await supabase.from("submissions").select("id,campaign_id,creator_id,posted_url,note,status,tracking_platform,created_at,campaigns(name,payment_rate,payment_method)").order("submitted_at",{ascending:false});if(e)setError("Could not load submissions.");setRows(data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function approveMetric(id:string){if(!supabase)return;const {data:v}=await supabase.from("metric_verifications").select("*").eq("submission_id",id).eq("status","pending").order("created_at",{ascending:false}).limit(1).maybeSingle();if(!v){setError("No pending metric verification found.");return}const {data:s}=await supabase.from("submissions").select("id,campaign_id,creator_id,creator_campaign_id,target_metric").eq("id",id).single();if(!s)return;const {data:campaign}=await supabase.from("campaigns").select("payment_method,payment_rate,max_budget").eq("id",s.campaign_id).single();const metric=Number(v.claimed_metric||0);await supabase.from("metric_verifications").update({status:"approved",reviewed_at:new Date().toISOString()}).eq("id",v.id);await supabase.from("submissions").update({current_metric:metric,metric_status:"target_reached",metric_verified_at:new Date().toISOString(),status:"approved"}).eq("id",id);if(campaign&&["views","cpm"].includes(String(campaign.payment_method).toLowerCase())&&metric>=Number(s.target_metric||0)){const {data:existing}=await supabase.from("campaign_payments").select("id").eq("submission_id",id).eq("type","creator_payment").maybeSingle();if(!existing){await supabase.from("campaign_payments").insert({campaign_id:s.campaign_id,creator_id:s.creator_id,submission_id:id,amount:Number(campaign.payment_rate||0)*Number(s.target_metric||0)/1000,type:"creator_payment",status:"released"})}}await load();setMessage("Metric verified and payment released when eligible.");setBusy("");return}
 async function update(id:string,status:"approved"|"changes_requested"){if(!supabase)return;setBusy(id);setError("");const {error:e}=await supabase.from("submissions").update({status}).eq("id",id);if(e)setError("Could not update submission.");else{setMessage(status==="approved"?"Submission approved.":"Changes requested.");await load()}setBusy("")}
 return <main className="formPage"><Link href="/admin" className="back">← Admin</Link><div className="formCard wide"><span className="eyebrow">ADMIN · REVIEW QUEUE</span><h1>Creator work <em>review.</em></h1><p>Monitor every submission and intervene when a campaign needs an admin decision.</p>{error&&<div className="successBox">{error}</div>}{message&&<div className="successBox">✓ {message}</div>}{loading?<div className="successBox">Loading submissions…</div>:<div className="opps">{rows.map(r=><article key={r.id}><b>{String(r.status).toUpperCase()}</b><h3>{r.campaigns?.name||"Campaign"}</h3><p>Creator: {r.creator_id}</p><p>{r.note||"No note provided"}</p>{r.tracking_platform==="snapchat"&&<div className="infoBox"><b>Snapchat evidence</b><p>Review the submitted Snapchat evidence link and public post before approving this submission.</p></div>}<a className="secondary" href={r.posted_url} target="_blank" rel="noreferrer">Open submitted work ↗</a>{r.status!=="approved"&&<div className="choiceRow"><button className="primary" disabled={!!busy} onClick={()=>update(r.id,"approved")}>{busy===r.id?"Saving…":"Approve"}</button><button className="secondary" disabled={!!busy} onClick={()=>update(r.id,"changes_requested")}>Request changes</button></div>}</article>)}{!rows.length&&<div className="successBox">No submissions yet.</div>}</div>}</div></main>
}